'use strict';

(() => {
  const GUIDES = {
    "Aftal ejerfordeling, fx 50/50 eller 60/40": {steps:["Vurder hvad hver ejer bidrager med i kapital, arbejdstid, kunder, ansvar og risiko.","Vælg en fordeling og aftal, om ekstra arbejde senere skal ændre ejerskabet eller betales som løn.","Skriv beslutningen ind i stiftelsesdokumentet, ejerbogen og ejeraftalen."],example:"Kladde: Emil ejer 50 %, Jesper ejer 50 %. Begge har samme stemmeret. Ændringer i ejerfordelingen kræver skriftlig enighed."},
    "Aftal hvem der indskyder hvor meget": {steps:["Notér kontant indskud, udstyr og eventuelle lån fra hver ejer.","Skeln mellem selskabskapital, ejerlån og private udlæg.","Aftal dato for indbetaling og gem dokumentation."],example:"Kladde: Emil indskyder 10.000 kr., Jesper indskyder 10.000 kr. Eventuelle ekstra beløb bogføres som ejerlån og tilbagebetales efter skriftlig aftale."},
    "Aftal roller og arbejdsfordeling": {steps:["Fordel salg, tilbud, udførelse, økonomi, indkøb og kundekontakt.","Beslut hvem der har det sidste driftsansvar på hvert område.","Planlæg en månedlig gennemgang af rollerne."],example:"Kladde: Emil har ansvar for salg, tilbud og kundekontakt. Jesper har ansvar for planlægning, materialer og kvalitet. Økonomi og større beslutninger er fælles."},
    "Aftal om begge skal være direktører": {steps:["Beslut om én eller begge registreres som direktør.","Beskriv hvem der må indgå aftaler og underskrive på selskabets vegne.","Kontrollér at tegningsreglen passer til jeres beslutning."],example:"Kladde: Begge ejere registreres som direktører. Aftaler over den interne beløbsgrænse kræver begge ejeres godkendelse."},
    "Aftal løn og eventuelle udlæg": {steps:["Aftal hvornår løn kan begynde, og om den er ens eller afhænger af arbejdstid.","Fastlæg regler for private udlæg, kørselsbilag og dokumentation.","Beslut hvem der godkender udbetalinger."],example:"Kladde: Der udbetales først løn, når likviditetsbudgettet tillader det. Udlæg refunderes kun mod bilag og registreres senest 14 dage efter købet."},
    "Beslut hvordan større beslutninger træffes": {steps:["Definér hvilke beslutninger der er større, fx lån, ansatte, biler og køb over en beløbsgrænse.","Aftal om de kræver enighed eller et bestemt flertal.","Dokumentér beslutningerne i et kort referat."],example:"Kladde: Lån, ansættelser, leasing og køb over 15.000 kr. kræver begge ejeres skriftlige godkendelse."},
    "Tal om, hvad der sker, hvis én vil ud af selskabet": {steps:["Aftal varsel, værdiansættelse og forkøbsret.","Beskriv hvordan igangværende arbejde, kunder og udstyr håndteres.","Få reglerne med i ejeraftalen."],example:"Kladde: En ejer giver 3 måneders skriftligt varsel. Den anden ejer får forkøbsret. Prisen fastsættes efter en på forhånd aftalt værdiansættelsesmetode."},
    "Udarbejd ejeraftale": {steps:["Saml jeres aftaler om ejerskab, arbejde, løn, beslutninger og exit.","Tilføj regler for sygdom, dødsfald, konkurrence, deadlock og misligholdelse.","Få aftalen gennemgået professionelt, før den underskrives."],example:"Start med overskrifterne: Ejerskab, arbejdspligt, beslutninger, løn, udbytte, forkøbsret, deadlock, sygdom/dødsfald, good/bad leaver og tvister."},
    "Regler om salg/overdragelse af anparter": {steps:["Beslut om anparter må sælges frit eller kræver samtykke.","Fastlæg proces, frister og dokumentation ved overdragelse.","Opdatér ejerbog og ejerregistrering efter et salg."],example:"Kladde: Anparter må ikke sælges eller pantsættes uden skriftligt samtykke fra den anden ejer og efter udløb af forkøbsretten."},
    "Forkøbsret": {steps:["Beslut hvem der får tilbudt anparterne først.","Fastlæg svarfrist, betalingsfrist og prisprincip.","Beskriv hvad der sker, hvis forkøbsretten ikke bruges."],example:"Kladde: Den anden ejer har 30 dage til at acceptere et skriftligt tilbud på samme vilkår som en ekstern køber."},
    "Håndtering af 50/50-deadlock": {steps:["Beskriv hvornår en fastlåst uenighed er en deadlock.","Indfør trin: nyt møde, ekstern mediator og derefter en aftalt exitmekanisme.","Undgå at en mindre uenighed automatisk kan udløse salg."],example:"Kladde: Uenigheden behandles på to møder med mindst 7 dages mellemrum. Derefter bruges mediator. Kan den stadig ikke løses, aktiveres den aftalte købs-/salgsprocedure."},
    "Good leaver/bad leaver": {steps:["Definér hvilke situationer der gør en ejer til good eller bad leaver.","Aftal hvordan anparterne værdiansættes i hver situation.","Sørg for at reglerne er proportionale og gennemgået juridisk."],example:"Kladde: Langvarig sygdom og aftalt fratræden er good leaver. Grov misligholdelse kan være bad leaver. Prisen fastsættes efter den aftalte model."},
    "Sygdom/dødsfald": {steps:["Aftal hvem der overtager driftsopgaver midlertidigt.","Overvej forsikring og finansiering af et eventuelt køb af anparter.","Beskriv arvingers og den tilbageværende ejers rettigheder."],example:"Kladde: Ved længerevarende sygdom overtager den anden ejer de nødvendige driftsopgaver. Ved dødsfald har den tilbageværende ejer forkøbsret efter ejeraftalens prisregel."},
    "Konkurrence- og kundeklausuler, hvor relevant": {steps:["Afgræns hvilke kunder, ydelser, områder og tidsperioder klausulen omfatter.","Undgå bredere begrænsninger end nødvendigt.","Få klausulen vurderet juridisk."],example:"Kladde: En udtrådt ejer må i den aftalte periode ikke aktivt kontakte selskabets eksisterende kunder med henblik på at overtage konkrete igangværende opgaver."},
    "Rettigheder til software, domæner, IP mv.": {steps:["List domæner, logo, billeder, tekster, skabeloner og software.","Notér hvem der ejer dem i dag.","Overdrag relevante rettigheder skriftligt til selskabet."],example:"Kladde: Domæne, logo, hjemmesidekode, tilbudsskabeloner og virksomhedens billeder overdrages vederlagsfrit til E&J ApS."},
    "Udbyttepolitik": {steps:["Aftal hvilke økonomiske krav der skal være opfyldt før udbytte.","Prioritér skat, drift, buffer og investeringer først.","Beslut om udbytte normalt fordeles efter ejerandel."],example:"Kladde: Udbytte kan kun foreslås, når selskabet har positiv likviditet, betalt forpligtelser og opretholder mindst tre måneders forventede faste omkostninger."},
    "Få evt. advokat til at gennemgå aftalen": {steps:["Saml den nyeste ejeraftale og en liste over åbne spørgsmål.","Bed om fokus på 50/50-deadlock, exit, værdiansættelse og klausuler.","Ret aftalen og få begge ejere til at godkende den endelige version."],example:"Mailkladde: Vi ønsker gennemgang af vores ejeraftale for et 50/50-ejet ApS, især deadlock, forkøbsret, good/bad leaver og sygdom/dødsfald."},
    "Vælg selskabsnavn": {steps:["Vælg et navn der passer til virksomhedens ydelser og brand.","Kontrollér at navnet ikke let forveksles med andre virksomheder eller beskyttede mærker.","Kontrollér også domæne og sociale profiler."],example:"Valgt navn: E&J ApS. Visningsnavn: E&J Total Byg & Enterprise. Domæne og e-mailnavn reserveres samtidig."},
    "Vælg adresse": {steps:["Vælg en lovlig adresse, hvor selskabet kan modtage post.","Aftal om adressen er privat, lejet eller hos en kontorudbyder.","Sørg for at ændringer registreres hurtigt."],example:"Kladde: Selskabets adresse er [vej, nummer, postnummer, by]. Post kontrolleres mindst to gange om ugen af [navn]."},
    "Fastlæg selskabets formål": {steps:["Beskriv virksomhedens vigtigste aktiviteter bredt nok til den forventede drift.","Medtag beslægtede aktiviteter uden at gøre teksten unødigt uklar.","Brug samme formulering i vedtægterne."],example:"Kladde: Selskabets formål er at udføre bygge-, renoverings-, vedligeholdelses- og serviceopgaver samt anden dermed beslægtet virksomhed."},
    "Fastlæg regnskabsår": {steps:["Vælg normalt kalenderåret, medmindre driften taler for andet.","Beslut længden på første regnskabsperiode.","Koordinér valget med bogholder eller revisor."],example:"Kladde: Regnskabsåret følger kalenderåret 1. januar–31. december. Første regnskabsår løber fra stiftelsen til 31. december."},
    "Udarbejd stiftelsesdokument": {steps:["Indsæt stiftere, kapital, tegningskurs, dato og ledelse.","Henvis til vedtægterne.","Kontrollér alle navne, adresser og beløb før underskrift."],example:"Dokumentet skal mindst identificere Emil og Jesper som stiftere, angive kapitalen og vise, hvem der indtræder i ledelsen."},
    "Udarbejd vedtægter": {steps:["Indsæt navn, formål, kapital, anparter, ledelse, tegningsregel og regnskabsår.","Sørg for at teksten passer til stiftelsesdokumentet.","Gem den underskrevne endelige version."],example:"Start med afsnit: 1 Navn, 2 Formål, 3 Kapital og anparter, 4 Ledelse, 5 Tegningsregel, 6 Generalforsamling, 7 Regnskabsår."},
    "Indbetal selskabskapital": {steps:["Få oplyst den korrekte indbetalingsmetode fra bank eller stiftelsesløsning.","Indbetal fra de aftalte ejere med tydelig tekst.","Gem kontoudtog og kvittering."],example:"Kladde: Begge ejere indbetaler deres aftalte andel med teksten “Selskabskapital E&J ApS”. Dokumentation gemmes i mappen Firmaoprettelse."},
    "Dokumentér kapitalen": {steps:["Brug bank, revisor eller anden accepteret dokumentationsmetode.","Kontrollér at beløb og selskabsoplysninger stemmer.","Gem dokumentationen sammen med stiftelsesmaterialet."],example:"Tjekliste: Beløb, indbetalingsdato, indbetaler, modtagerkonto og erklæring/kontoudtog skal kunne kobles entydigt til stiftelsen."},
    "Registrér ApS'et hos Erhvervsstyrelsen": {steps:["Indsaml stiftelsesdokument, vedtægter, kapitaldokumentation og ejeroplysninger.","Kontrollér ledelse, tegningsregel, adresse og brancheoplysninger.","Gem kvittering og sagsnummer efter indsendelse."],example:"Før indsendelse: kontrollér navn, adresse, formål, kapital, ejerandele, direktører, regnskabsår og reelle ejere én gang til."},
    "Modtag CVR-nummer": {steps:["Gem registreringsbeviset og CVR-nummeret centralt.","Brug CVR på fakturaer, bank, forsikring, hjemmeside og aftaler.","Kontrollér at de offentlige oplysninger er korrekte."],example:"Når CVR modtages: opdatér firmamailens signatur, fakturaskabelon, tilbud, hjemmeside og bankansøgning samme dag."},
    "Opret ejerbog": {steps:["Registrér ejernes navn, adresse, ejerandel og dato for erhvervelse.","Notér senere overdragelser og pantsætninger.","Gem ejerbogen sikkert og hold den opdateret."],example:"Kladde: Emil – 50 % – erhvervet på stiftelsesdatoen. Jesper – 50 % – erhvervet på stiftelsesdatoen."},
    "Registrér legale ejere": {steps:["Identificér alle ejere over den relevante registreringsgrænse.","Indtast ejerandel og stemmerettigheder korrekt.","Opdatér registreringen ved ændringer."],example:"Kladde: Emil registreres med 50 % kapital og stemmer. Jesper registreres med 50 % kapital og stemmer."},
    "Registrér reelle ejere": {steps:["Vurder hvem der i sidste ende ejer eller kontrollerer selskabet.","Registrér ejerandel, stemmer og eventuel kontrol på anden måde.","Gem grundlaget for vurderingen."],example:"Kladde: Emil og Jesper registreres begge som reelle ejere med 50 % direkte ejerskab, hvis de ejer privat og ikke via holdingselskaber."},
    "Overvej om I skal eje privat eller via hvert jeres holdingselskab inden strukturen låses fast": {steps:["Sammenlign enkelhed, omkostninger, risiko og planer om senere salg eller investering.","Få konkret rådgivning om skat og selskabsstruktur.","Træf beslutningen før den endelige stiftelse, hvis muligt."],example:"Beslutningsnotat: Privat ejerskab er enklest nu. Holding vælges kun, hvis fordelene ved risikoadskillelse og fremtidig kapital opvejer ekstra administration."},
    "Opret erhvervskonto": {steps:["Saml CVR, ejeroplysninger, budget, forretningsbeskrivelse og legitimation.","Ansøg hos den valgte bank og svar hurtigt på kundekendskabsspørgsmål.","Aftal adgang, godkendelsesregler og firmakort."],example:"Bankpakken: CVR-bevis, vedtægter, ejerbog, budget, beskrivelse af kunder/ydelser, forventet omsætning og legitimation for Emil og Jesper."},
    "Registrér selskabet for moms, hvis relevant": {steps:["Vurder om og fra hvilken dato selskabet skal momsregistreres.","Registrér forventet omsætning og aktivitet korrekt.","Opsæt bogføringen til salgsmoms og købsmoms."],example:"Kladde til bogholder: Vi forventer at fakturere bygge- og serviceydelser fra [dato] og ønsker afklaring af momsregistrering og første indberetningsperiode."},
    "Registrér som arbejdsgiver, hvis I skal have løn": {steps:["Beslut hvornår første løn skal udbetales.","Registrér selskabet som arbejdsgiver inden lønkørslen.","Vælg lønsystem og aftal ansvar for indberetning."],example:"Kladde: Første lønkørsel planlægges til [dato]. [Navn/bogholder] opsætter lønsystem, skat, ferie og lønsedler."},
    "Vælg bogføringssystem": {steps:["Sammenlign fakturering, bankintegration, bilag, løn og adgang for bogholder.","Vælg et system der passer til jeres størrelse og branche.","Opsæt kontoplan, brugere og godkendelsesflow."],example:"Kravliste: mobil bilagsscanning, bankafstemning, tilbud/faktura, projekter, adgang til begge ejere og bogholder samt eksport til årsrapport."},
    "Opsæt fakturering": {steps:["Lav nummerserie, betalingsbetingelser og standardtekster.","Indsæt selskabsnavn, adresse, CVR, bank og kontaktoplysninger.","Test en kladdefaktura før den første kunde."],example:"Standard: 8 dages betalingsfrist, fakturanummer, arbejdssted, ydelsesbeskrivelse, beløb, moms, samlet beløb og betalingsoplysninger."},
    "Opsæt bilag/kvitteringer": {steps:["Vælg én fast metode til at fotografere og indsende bilag.","Kræv dato, leverandør, beløb, formål og projekt/kunde.","Afstem manglende bilag mindst månedligt."],example:"Rutine: Bilag fotograferes samme dag, mærkes med kunde/projekt og sendes til bogføringssystemet. Private udlæg markeres med ejerens navn."},
    "Lav budget og likviditetsbudget": {steps:["Budgettér omsætning, materialer, løn, biler, forsikringer og administration måned for måned.","Indregn moms, skat og langsomme kundebetalinger.","Følg faktisk resultat og bankbeholdning op hver måned."],example:"Start med 6 måneder: forventede fakturaer, betalingsdatoer, materialekøb, faste udgifter, løn, moms og minimumsbuffer."},
    "Aftal med revisor/bogholder, hvem der håndterer moms, løn og årsrapport": {steps:["List alle tilbagevendende økonomiopgaver.","Fordel ansvar, frister og godkendelser mellem jer og rådgiveren.","Få pris og leverance på skrift."],example:"Kladde: Bogholder bogfører og afstemmer månedligt samt klargør moms. Ejerne godkender. Revisor udarbejder årsrapport og skatteoplysninger."},
    "Køb domæne": {steps:["Vælg et kort domæne der matcher selskabsnavnet.","Registrér det i selskabets navn eller overdrag det straks efter stiftelsen.","Slå automatisk fornyelse og tofaktorlogin til."],example:"Tjek både hoveddomæne og almindelige stavevarianter. Gem login i virksomhedens passwordmanager, ikke på en privat konto alene."},
    "Opret firma-mail": {steps:["Opret personlige adresser og en fælles adresse.","Opsæt signatur med selskabsoplysninger.","Slå tofaktorlogin, videresendelse og backup til."],example:"Forslag: emil@..., jesper@..., info@... og faktura@.... Begge ejere skal have adgang til de relevante fælles postkasser."},
    "Tegn relevante forsikringer": {steps:["Beskriv ydelser, omsætning, ansatte, biler, værktøj og typiske skader.","Indhent tilbud på ansvar, arbejdsskade og relevante brancheforsikringer.","Sammenlign selvrisiko, dækningssummer og undtagelser."],example:"Spørg forsikringsselskabet om erhvervsansvar, produktansvar, arbejdsskade ved ansatte, værktøj, biler og retshjælp."},
    "Lav standardtilbud/-kontrakter": {steps:["Indsæt præcis opgavebeskrivelse, pris, materialer, tidsplan og forbehold.","Beskriv ændringer, ekstraarbejde, betaling og aflevering.","Tilpas skabelonen til hver kunde."],example:"Skabelon: Omfang, hvad der ikke er med, pris/moms, betalingsplan, start/slut, kundens ansvar, ekstraarbejde, forsinkelse og acceptfelt."},
    "Lav handelsbetingelser, hvis relevant": {steps:["Beskriv betaling, forsinkelse, reklamation, ansvar og aflysning.","Sørg for at betingelserne passer til privat- eller erhvervskunder.","Få dem accepteret sammen med tilbuddet."],example:"Kladdeoverskrifter: Betaling, kundens medvirken, adgang til arbejdssted, ekstraarbejde, forsinkelse, reklamation, ansvar, afbestilling og tvister."},
    "GDPR/persondatapolitik": {steps:["List hvilke personoplysninger I modtager om kunder, ansatte og leverandører.","Beskriv formål, opbevaring, adgang, sletning og rettigheder.","Begræns oplysningerne til det nødvendige."],example:"Kladde: Vi behandler navn, kontaktoplysninger, adresse, aftaler, fakturaer og relevante billeder for at levere og dokumentere arbejdet."},
    "Databehandleraftaler, hvis nødvendigt": {steps:["List leverandører der behandler persondata for jer, fx mail, løn, regnskab og cloud.","Kontrollér om de tilbyder en databehandleraftale.","Gem aftalerne centralt og gennemgå dem ved leverandørskifte."],example:"Tjekliste: mailudbyder, bogføringssystem, lønsystem, cloudlager, CRM, bookingsystem og eventuel hjemmesideleverandør."},
    "Overfør relevante IP-rettigheder til selskabet": {steps:["Find aktiver der er oprettet privat før selskabet.","Beskriv dem entydigt i en overdragelseserklæring.","Flyt konti, licenser og registrantoplysninger til selskabet."],example:"Kladde: Emil og Jesper overdrager logo, domæner, tekster, billeder, skabeloner og kode til E&J ApS fra stiftelsesdatoen."},
    "Sørg for at alle aftaler mellem jer er på skrift": {steps:["Saml beslutninger i ejeraftale, referater eller korte skriftlige tillæg.","Brug dato, beslutning, ansvarlig og begge ejeres godkendelse.","Gem dokumenterne i én fælles mappe."],example:"Referatsskabelon: Dato, deltagere, beslutning, økonomisk konsekvens, ansvarlig, deadline og godkendelse fra Emil og Jesper."},
    "Undgå private og selskabets penge på samme konto": {steps:["Brug kun selskabets konto til selskabets indtægter og udgifter.","Registrér private udlæg særskilt med bilag.","Undgå private hævninger uden korrekt løn, udbytte eller tilbagebetaling."],example:"Rutine: Alle kundebetalinger går til erhvervskontoen. Private udlæg indsendes med bilag og refunderes via bogføringen."},
    "Aftal godkendelsesgrænser for større køb": {steps:["Fastlæg beløbsgrænser for én ejer og for fælles godkendelse.","Definér regler for akutte køb og faste abonnementer.","Brug samme regler på bank og firmakort hvor muligt."],example:"Kladde: Køb op til 5.000 kr. kan godkendes af den ansvarlige. Køb over 5.000 kr., leasing og nye abonnementer kræver begge ejeres godkendelse."},
    "Aftal månedlig økonomiopfølgning": {steps:["Book et fast møde hver måned.","Gennemgå bank, debitorer, kreditorer, moms, budget og kommende investeringer.","Fordel opgaver og gem et kort referat."],example:"Fast agenda: bankbeholdning, faktureret, ikke-betalt, kommende regninger, moms/skatter, budgetafvigelser og beslutninger til næste måned."},
    "Lav plan for de første 3–6 måneders kapitalbehov": {steps:["Beregn lavt, forventet og højt salgsscenarie.","Indregn materialer før kundebetaling, biler, værktøj, løn og moms.","Fastlæg minimumsbuffer og hvad I gør, hvis salget bliver forsinket."],example:"Plan: månedlig begyndelsesbeholdning + indbetalinger − materialer − faste udgifter − løn − moms = slutbeholdning. Markér den laveste forventede saldo."}
  };

  let activeCard = null;
  let scheduled = false;
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

  function genericGuide(title) {
    return {steps:['Skriv det ønskede resultat med én klar sætning.','Fordel ansvar mellem Emil, Jesper eller Fælles og vælg en realistisk tidsfrist.','Gem beslutningen eller dokumentationen i opgavens noter.'],example:`Kladde: ${title}. Ansvarlig: [navn]. Næste handling: [skriv handling]. Tidsfrist: [dato].`};
  }
  function ensureDialog() {
    if (document.getElementById('taskHelpDialog')) return;
    const dialog = document.createElement('dialog');
    dialog.id = 'taskHelpDialog';
    dialog.className = 'task-help-dialog';
    dialog.innerHTML = `<div class="task-help-card"><div class="task-help-heading"><div><span class="task-help-kicker">Opgaveløser</span><h2 id="taskHelpTitle">Forslag til løsning</h2></div><button type="button" class="task-help-close" aria-label="Luk">×</button></div><div class="task-help-body"><h3>Sådan kan I løse opgaven</h3><ol id="taskHelpSteps"></ol><h3>Eksempel på en løsning</h3><div id="taskHelpExample" class="task-help-example"></div><p class="task-help-note">Eksemplet er en kladde. Juridiske, skattemæssige og økonomiske dokumenter bør kontrolleres af den relevante rådgiver.</p></div><div class="task-help-actions"><button type="button" id="copyTaskHelpBtn" class="button">Kopiér eksempel</button><button type="button" id="useTaskHelpBtn" class="button primary">Brug som kladde i noter</button><button type="button" class="button task-help-close">Luk</button></div></div>`;
    document.body.appendChild(dialog);
    dialog.addEventListener('click', (event) => { if (event.target === dialog || event.target.closest('.task-help-close')) dialog.close(); });
    document.getElementById('copyTaskHelpBtn').addEventListener('click', async () => {
      const text = document.getElementById('taskHelpExample').textContent;
      try { await navigator.clipboard.writeText(text); } catch { prompt('Kopiér eksemplet:', text); }
    });
    document.getElementById('useTaskHelpBtn').addEventListener('click', () => {
      if (!activeCard) return;
      const textarea = activeCard.querySelector('textarea[data-field="notes"]');
      if (!textarea) return;
      const example = document.getElementById('taskHelpExample').textContent.trim();
      textarea.value = textarea.value.trim() ? `${textarea.value.trim()}\n\nForslag til løsning:\n${example}` : `Forslag til løsning:\n${example}`;
      textarea.dispatchEvent(new Event('change', {bubbles:true}));
      dialog.close();
    });
  }
  function openGuide(card) {
    ensureDialog(); activeCard = card;
    const title = card.querySelector('.task-title')?.textContent?.trim() || 'Opgave';
    const guide = GUIDES[title] || genericGuide(title);
    document.getElementById('taskHelpTitle').textContent = title;
    document.getElementById('taskHelpSteps').innerHTML = guide.steps.map((step) => `<li>${esc(step)}</li>`).join('');
    document.getElementById('taskHelpExample').textContent = guide.example;
    document.getElementById('taskHelpDialog').showModal();
  }
  function decorateCards() {
    scheduled = false;
    document.querySelectorAll('.task-card').forEach((card) => {
      const actions = card.querySelector('.task-actions');
      if (!actions || actions.querySelector('[data-task-help]')) return;
      const button = document.createElement('button');
      button.type = 'button'; button.className = 'task-help-button'; button.dataset.taskHelp = '1'; button.textContent = '?'; button.title = 'Se forslag til løsning';
      actions.prepend(button);
    });
  }
  function scheduleDecorate() { if (scheduled) return; scheduled = true; requestAnimationFrame(decorateCards); }
  document.addEventListener('DOMContentLoaded', () => {
    ensureDialog();
    const root = document.getElementById('taskRoot'); if (!root) return;
    new MutationObserver(scheduleDecorate).observe(root, {childList:true,subtree:true});
    root.addEventListener('click', (event) => { const button = event.target.closest('[data-task-help]'); if (!button) return; event.preventDefault(); event.stopPropagation(); openGuide(button.closest('.task-card')); }, true);
    scheduleDecorate();
  });
})();
